[package]
name = "gondola-rs"
version = "0.2.1"
authors = ["Kevin Robert Stravers <macocio@gmail.com>"]
edition = "2018"

[dependencies]
actix-files = "0.1.4"
actix-service = "0.4.2"
actix-web = "1.0.7"
chrono = "0.4"
fast-logger = "0.6.0"
file-rotate = "0.1.1"
gameshell = "0.1.0"
indexmap = "1.2.0"
maud = "0.21.0"
rand = "0.7.2"
rand_pcg = "0.2.0"
serde = "1.0.101"
serde_derive = "1.0.101"
