[package]
name = "gondola-rs"
version = "0.2.1"
authors = ["Kevin Robert Stravers <macocio@gmail.com>"]
edition = "2018"

[dependencies]
actix-files = "0.2.1"
actix-service = "1.0.5"
actix-web = "2.0.0"
actix-rt = "1.0.0"
chrono = "0.4.10"
fast-logger = "0.6.0"
file-rotate = "0.1.1"
gameshell = "0.1.1"
indexmap = "1.3.2"
maud = "0.21.0"
rand = "0.7.3"
rand_pcg = "0.2.1"
serde = "1.0.104"
serde_derive = "1.0.104"
