[package]
name = "gondola-rs"
version = "0.2.1"
authors = ["Kevin Robert Stravers <macocio@gmail.com>"]
edition = "2018"

[dependencies]
actix-files = "0.4.1"
actix-service = "1.0.6"
actix-web = "3.3.2"
actix-rt = "1.1.1"
chrono = "0.4.19"
fast-logger = "0.6.0"
file-rotate = "0.4.0"
gameshell = "0.4.0"
indexmap = "1.6.0"
maud = "0.22.1"
rand = "0.7.3"
rand_pcg = "0.2.1"
serde = "1.0.118"
serde_derive = "1.0.118"
